# Generated by Django 4.1.3 on 2022-11-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=40)),
                ('answer', models.CharField(max_length=20)),
                ('opt1', models.CharField(max_length=20)),
                ('opt2', models.CharField(max_length=20)),
                ('opt3', models.CharField(max_length=20)),
                ('opt4', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
