# Generated by Django 4.1.3 on 2022-11-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'managed': True, 'verbose_name': 'Tests', 'verbose_name_plural': 'Tests'},
        ),
        migrations.RemoveField(
            model_name='test',
            name='opt4',
        ),
    ]
